[package]
name = "signature-verify"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
solana-program = "=2.0.5"
sha2 = "0.10.8"
borsh = {version = "1.2.1", features = ["derive"]}
rand = "0.8.5"
libsecp256k1 = "0.7.1"

[lib]
crate-type = ["cdylib", "lib"]
